# Site settings
title: Experience variety
email: cfollet@protonmail.com
author: Charles Follet
description: "A blog about ..."
baseurl: ""
url: "cfollet.github.io"
twitter_username: charlesfollet
github_username:  cfollet
linkedin_username: cfollet

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems:
  - jekyll-sitemap
  - jekyll-paginate