# Permalinks
permalink:           pretty

# Setup
title:               CF
tagline:             Another computer science blog.
url:                 http://cfollet.github.io
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Charles Follet
  url:               http://cfollet.github.io
  email:             charles.follet@yahoo.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/cfollet/cfollet.github.io

# Gems
gems:
  - jekyll-gist
